timeout: 14400s
steps:
- name: gcr.io/cloud-builders/git
  dir: "go/src/k8s.io"
  args:
  - "clone"
  - "--branch=${_RELEASE_TOOL_BRANCH}"
  - "${_RELEASE_TOOL_REPO}"

- name: k8s.gcr.io/kube-cross:${_KUBE_CROSS_VERSION}
  dir: "go/src/k8s.io/release"
  env:
  - "GOPATH=/workspace/go"
  - "GOBIN=/workspace/bin"
  - "GO111MODULE=on"
  - "GOPROXY=https://proxy.golang.org"
  - "GOSUMDB=sum.golang.org"
  args:
  - "./compile-release-tools"

- name: gcr.io/$PROJECT_ID/k8s-cloud-builder
  dir: "go/src/k8s.io/release"
  env:
  - "RELEASE_TOOL_REPO=${_RELEASE_TOOL_REPO}"
  - "RELEASE_TOOL_BRANCH=${_RELEASE_TOOL_BRANCH}"
  args:
  - "./anago"
  - "${_RELEASE_BRANCH}"
  - "--stage"
  - "--prebuild"
  - "${_BUILD_AT_HEAD}"
  - "${_NOMOCK}"
  - "${_OFFICIAL}"
  - "${_BUILDVERSION}"
  - "${_RC}"
  - "--yes"
  - "--gcb"
  - "--basedir=/workspace"
  - "--tmpdir=/workspace/tmp"

- name: k8s.gcr.io/kube-cross:local
  dir: "go/src/k8s.io/release"
  env:
  - "RELEASE_TOOL_REPO=${_RELEASE_TOOL_REPO}"
  - "RELEASE_TOOL_BRANCH=${_RELEASE_TOOL_BRANCH}"
  args:
  - "./anago"
  - "${_RELEASE_BRANCH}"
  - "--stage"
  - "--buildonly"
  - "${_BUILD_AT_HEAD}"
  - "${_NOMOCK}"
  - "${_OFFICIAL}"
  - "${_BUILDVERSION}"
  - "${_RC}"
  - "--yes"
  - "--gcb"
  - "--basedir=/workspace"
  - "--tmpdir=/workspace/tmp"

- name: gcr.io/$PROJECT_ID/k8s-cloud-builder
  dir: "go/src/k8s.io/release"
  env:
  - "RELEASE_TOOL_REPO=${_RELEASE_TOOL_REPO}"
  - "RELEASE_TOOL_BRANCH=${_RELEASE_TOOL_BRANCH}"
  args:
  - "./anago"
  - "${_RELEASE_BRANCH}"
  - "--stage"
  - "${_BUILD_AT_HEAD}"
  - "${_NOMOCK}"
  - "${_OFFICIAL}"
  - "${_BUILDVERSION}"
  - "${_RC}"
  - "--yes"
  - "--gcb"
  - "--basedir=/workspace"
  - "--tmpdir=/workspace/tmp"

tags:
- ${_GCP_USER_TAG}
- ${_RELEASE_BRANCH}
- ${_BUILD_POINT}
- ${_NOMOCK_TAG}
- ${_OFFICIAL_TAG}
- ${_RC_TAG}
- STAGE

options:
  machineType: N1_HIGHCPU_32
