# See https://cloud.google.com/cloud-build/docs/build-config
timeout: 1200s
options:
  substitution_option: ALLOW_LOOSE
steps:
  - name: gcr.io/cloud-builders/docker
    args:
    - build
    - --tag=gcr.io/$PROJECT_ID/k8s-gcb-base:$_GIT_TAG
    - --tag=gcr.io/$PROJECT_ID/k8s-gcb-base:latest
    - .
substitutions:
  # _GIT_TAG will be filled with a git-based tag for the image, of the form vYYYYMMDD-hash, and
  # can be used as a substitution
  _GIT_TAG: '12345'
  _PULL_BASE_REF: 'dev'
images:
  - 'gcr.io/$PROJECT_ID/k8s-gcb-base:$_GIT_TAG'
  - 'gcr.io/$PROJECT_ID/k8s-gcb-base:latest'
